---
linters:
  ErbSafety:
    enabled: true
  ExtraNewline:
    enabled: true
  FinalNewline:
    enabled: true
  SelfClosingTag:
    enabled: false
  SpaceAroundErbTag:
    enabled: true
  SpaceIndentation:
    enabled: true
  SpaceInHtmlTag:
    enabled: true
  TrailingWhitespace:
    enabled: true
  Rubocop:
    enabled: true
    only:
      - Layout/EndOfLine
      - Layout/SpaceAfterColon
      - Layout/SpaceAfterComma
      - Layout/SpaceAfterMethodName
      - Layout/SpaceAfterNot
      - Layout/SpaceAfterSemicolon
      - Layout/SpaceAroundBlockParameters
      - Layout/SpaceAroundOperators
      - Layout/SpaceBeforeBlockBraces
      - Layout/SpaceBeforeComma
      - Layout/SpaceBeforeComment
      - Layout/SpaceBeforeFirstArg
      - Layout/SpaceBeforeSemicolon
      - Layout/SpaceInsideArrayLiteralBrackets
      - Layout/SpaceInsideArrayPercentLiteral
      - Layout/SpaceInsideBlockBraces
      - Layout/SpaceInsideHashLiteralBraces
      - Layout/SpaceInsideParens
      - Layout/SpaceInsidePercentLiteralDelimiters
      - Layout/SpaceInsideRangeLiteral
      - Layout/SpaceInsideReferenceBrackets
      - Layout/SpaceInsideStringInterpolation
      - Layout/Tab
      - Lint/LiteralAsCondition
      - Style/PercentLiteralDelimiters
