staging:
  deploy_to: "/var/www/consul"
  ssh_port: 21
  server: "staging.consul.es"
  db_server: "postgre.consul.es"
  user: "xxxxx"
  server_name: "staging.consul.es"
  full_app_name: "consul"

preproduction:
  deploy_to: "/var/www/consul"
  ssh_port: 2222
  server1: xxx.xxx.xxx.xxx
  server2: xxx.xxx.xxx.xxx
  db_server: xxx.xxx.xxx.xxx
  user: xxxxx
  server_name: pre.consul.es
  full_app_name: "consul"

production:
  deploy_to: "/home/deploy/consul"
  ssh_port: 22
  server1: 167.71.5.9
  db_server: "localhost"
  user: "deploy"
  server_name: "167.71.5.9"
  full_app_name: "consul"
